      - file: "components.json"
        label: "Site Settings"
        name: "site_settings"
        fields:
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "SEO Keywords", name: "seoKeywords", widget: "string"}
          - {label: "Primary Neon", name: "primaryNeon", widget: "color"}
          - {label: "Secondary Neon", name: "secondaryNeon", widget: "color"}
          - {label: "Accent Neon", name: "accentNeon", widget: "color"}
