backend:
  name: git-gateway
  branch: main
repo: IBM-TECH/Updated-website

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "settings"
    label: "Settings"
    files:
      - file: "components.json"
        label: "Site Settings"
        name: "site_settings"
        fields:
          - {label: "Portfolio Name", name: "name", widget: "string"}
          - {label: "Artist Bio", name: "bio", widget: "text"}

